git:
  depth: 10
notifications:
  email:
     on_success: always
     on_failure: always
language: csharp
python: '2.7'
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -q update && sudo apt-get -q -y --no-install-recommends install libfl-dev libfl-dev:i386; fi
  - wget 'https://ci.appveyor.com/api/projects/markfinal/buildamation/artifacts/bam.tar?branch=master&job=Image%3A%20Visual%20Studio%202017' -O /tmp/bam.tar
  - mkdir -p /tmp/BuildAMation
  - tar xf /tmp/bam.tar -C /tmp/BuildAMation
  - if [ $TRAVIS_OS_NAME = linux ]; then wget 'https://ci.appveyor.com/api/projects/markfinal/buildamation/artifacts/ubuntu_install_scripts.tar?branch=master&job=Image%3A%20Visual%20Studio%202017' -O /tmp/ubuntu_install_scripts.tar; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then tar xf /tmp/ubuntu_install_scripts.tar -C /tmp; fi
before_script:
  - dotnet --version
matrix:
  include:
  - os: linux
    dist: xenial
    mono: none
    dotnet: 2.1.401
    name: Ubuntu 16 (GCC 9) Native
    env:
      - BAM_BUILD_MODE=Native
      - BAM_TOOLCHAIN_NAME=Gcc
      - BAM_TOOLCHAIN_VERSION=9
script:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo /tmp/CI/ubuntu_install_scripts/install_gcc.sh ${BAM_TOOLCHAIN_VERSION} && sudo /tmp/CI/ubuntu_install_scripts/enable_gcc.sh ${BAM_TOOLCHAIN_VERSION}; fi
  - source /tmp/BuildAMation/env.sh && python /tmp/BuildAMation/tests/runtests.py --${BAM_TOOLCHAIN_NAME}.version=${BAM_TOOLCHAIN_VERSION} -c debug -c profile -j0 -d --nodefaultrepo -r . -b $BAM_BUILD_MODE $EXTRA_TEST_ARGS
